app:
  title: Data Science Backstage
  baseUrl: http://localhost:3000

organization:
  name: Best Egg
  githubOrg: canal-consulting

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    pluginDivisionMode: schema
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  cache:
    store: memory
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      apps:
        - appId: ${AUTH_GITHUB_APP_ID}
          clientId: ${AUTH_GITHUB_CLIENT_ID}
          clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
          privateKey: ${AUTH_GITHUB_PRIVATE_KEY}
          webhookSecret: ${AUTH_GITHUB_WEBHOOK_SECRET}


proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

scaffolder:
  defaultAuthor:
    name: Backstage App Creator
    email: backstage@bestegg.com
  defaultCommitMessage: "New app created"

catalog:
  providers:
    github:
      providerId:
        organization: 'canal-consulting'
        catalogPath: '/catalog-info.yaml'
    wildcardProviderId:
      organization: 'canal-consulting' # string
      catalogPath: '/**/*.yaml'
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Domain]
  locations:
    - type: url
      target: https://github.com/canal-consulting/backstage-templates/blob/main/terraform-module/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/canal-consulting/ds-team/blob/main/organization/catalog-info.yaml
      rules:
        - allow: [Group, Domain, User, Location, Resource, API, System, Component]
    - type: file
      target: ../../scaffolder/docs-template/template.yaml
      rules:
        - allow: [Template, User, Group]
